### ISSUE TITLE
NaNs in JSON data

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan_webapp#28]
![image](https://user-images.githubusercontent.com/7894397/64537271-6cd0b500-d312-11e9-9e34-9b8416d9567c.png)
Sometimes NaNs still appear (I believe in the registration scalars). I can't find a reliable way to reproduce it, but it occasionally still happens under certain conditions.

How should I handle these?

**Comment by JoshuaSteer** [comment]
Ahhh, can you send an example where this happens?

**Comment by jack-parsons** [comment]
A scenario I found is if you get 2 objects very poorly aligned like in the picture.
![image](https://user-images.githubusercontent.com/7894397/64542556-afe35600-d31b-11e9-9b2b-20930f2bb341.png)

**Comment by JoshuaSteer** [comment]
Could you save them both and send to me?
