### ISSUE TITLE
Save function

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan_webapp#3]
Choose which object to save - three dots

**Comment by jack-parsons** [comment]
@JoshuaSteer Currently it's saving as an stl file for a single, however this doesn't contain the registration scalar data, and only really would be downloading the same stl file the user uploaded (except transformations). Is this what you are looking for, or would it be better to save entire environment?

**Comment by JoshuaSteer** [comment]
Yeah, need to work out the best way to save these files. Just do .stl for the moment and we'll consider alternatives, maybe using a .pkl file?

**Comment by jack-parsons** [comment]
That could work quite nicely, but would only be readable by our own software of course.

On a separate issue, I found that due to security reasons, it's not really possible to choose a download location, so have to download to default location. https://stackoverflow.com/questions/34870711/download-a-file-at-different-location-using-html5

**Comment by JoshuaSteer** [comment]
Well it's readable by the AmpScan package not just the software. We can build in a load of standard outputs beyond .stl which can accept scalar data (.ply etc) 

Argh, fair enough. Thanks for checking
