### ISSUE TITLE
Alignment Fixes

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan_webapp#34]
Icons to alignment views to indicate correct orientation, such as front on, side on.
<img src="https://user-images.githubusercontent.com/7894397/65195236-52b37700-da76-11e9-8b19-d7e74a554004.png" alt="image" width=64px height=64px><img src="https://user-images.githubusercontent.com/7894397/65195350-d705fa00-da76-11e9-9c9f-40c3dcd269a5.png" alt="image" width=64px height=64px>
Add test to make sure that e.g. it's not vertical when it should be horizontal before registration/end of alignment, as a sanity check for user.
This will help with stopping invalid CSA calculations due to incorrect orientation of scans.

**Comment by JoshuaSteer** [comment]
- [x] Add text into the 4 windows 
- [x] Make sure manual alignment changes are pushed to the server

**Comment by JoshuaSteer** [comment]
- [ ] Add 3 point alignment
