### ISSUE TITLE
Scalar bar

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan_webapp#4]
For registration

**Comment by JoshuaSteer** [comment]
@jack-parsons There exists a white box under the scalar bar - can that be removed?

**Comment by JoshuaSteer** [comment]
![image](https://user-images.githubusercontent.com/22979985/64711601-c28f9380-d4b1-11e9-9807-b03a4be3e4c0.png)

**Comment by jack-parsons** [comment]
Should I make the bar go right down to the bottom or make the bg colour match?
