### ISSUE TITLE
Live updating analyse graphs

### ISSUE THREAD

**Issue by jack-parsons** [abel-research/ampscan_webapp#9]

**Comment by jack-parsons** [comment]
@JoshuaSteer what graphs would you like, and would they come under the registration or analyse tab?

**Comment by JoshuaSteer** [comment]
Analyse I think. Just start with csa along limb

**Comment by jack-parsons** [comment]
Added CSA graph on registration for target and baseline scans

**Comment by jack-parsons** [comment]
- [ ] Add live histogram
0 centered on white
Odd number of bins
